package com.sh.object.ch02.step01.mine.enumClazz;

public enum Genre {

    ROMANCE, COMEDY, ROMANTIC_COMEDY, ANIMATION, HORROR, THRILLER, DRAMA,
    ACTION, SCIENCE_FICTION, FANTASY, TIMELESS_CLASSIC, DOCUMENTARY;
}
